name: timberr
description: A furniture shopping app made using Flutter, Firebase and Getx state management.

publish_to: 'none'

version: 2.0.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  lottie: ^3.0.0
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  model_viewer_plus: ^1.7.2

dependency_overrides:
  win32: ^5.5.0
  archive: ^4.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
  - assets/
  - assets/icons/
  - assets/lottie/
  - assets/fonts/
  - assets/slider/
  - assets/3dmodel/

  fonts:
  - family: NunitoSans
    fonts:
      - asset: assets/fonts/NunitoSans_Regular.ttf
      - asset: assets/fonts/NunitoSans_Light.ttf
        weight: 300
      - asset: assets/fonts/NunitoSans_SemiBold.ttf
        weight: 600
      - asset: assets/fonts/NunitoSans_Bold.ttf
        weight: 700
      - asset: assets/fonts/NunitoSans_ExtraBold.ttf
        weight: 800

  - family: Gelasio
    fonts:
      - asset: assets/fonts/Gelasio_Regular.ttf
      - asset: assets/fonts/Gelasio_Medium.ttf
        weight: 500
      - asset: assets/fonts/Gelasio_SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Gelasio_Bold.ttf
        weight: 700

  - family: Merriweather
    fonts:
      - asset: assets/fonts/Merriweather_Regular.ttf
      - asset: assets/fonts/Merriweather_Bold.ttf
        weight: 700